CSS added for #5 & #6
toth2000/chatBit pull request #9
Opened 2021-07-21 18:59 UTC by alvarotorrestx

- Added CSS for Issues #5 & #6 
- added css aligning for chat.css
- added css alignment and style for input.css (button also - wasn't sure if wanted)
- added import for input.css on the input.jsx as it was missing
- updated index.js as it was crashing on local running for not finding 'app.js' <- not sure if only a local problem

2021-07-22 04:32 UTC, toth2000 commented
Thanks for the PR. I will check and merge it soon ( I have an exam today, so I will check later).  And please always make changes on code into a separate branch (other than main/master) while making PR in any repository as it is recommended by everyone.

2021-07-22 05:30 UTC, alvarotorrestx commented
Definitely will! Thank you for that tip, will proceed to do further on further PRs!

2021-07-22 17:53 UTC, toth2000 requested changes
Any reason why you have deleted 22,382 lines of code from the package-lock.json file?
Other than that everything looks fine.

Please make the suggested changes on the branch that you have used on this pull request.
Let me know once done.

2021-07-22 17:53 UTC, toth2000 commented on src/index.js
> +import App from './App';
this should be 
```
import App from './app';
```

2021-07-22 19:23 UTC, alvarotorrestx commented on src/index.js
> +import App from './App';
Thank you, updated!

2021-07-22 19:24 UTC, alvarotorrestx commented
> Any reason why you have deleted 22,382 lines of code from the package-lock.json file?
> Other than that everything looks fine.
> 
> Please make the suggested changes on the branch that you have used on this pull request.
> Let me know once done.

I'm really not sure what happened on that deletion or where it came from, I see all the files but I do see where it marks it as deleted, I do apologize for that, I'll look further into it

As per the corrections after review, I have submitted that and thank you!

I'm still learning how to fully use git and github to the best ability so I do apologize for any delay

2021-07-23 05:24 UTC, toth2000 commented
@alvarotorrestx  No worries! You are doing great. And Thank you for your contribution.  I will merge it soon.

2021-07-23 05:35 UTC, toth2000 commented
Merging this branch. Thank you for your contributions.!!

2021-07-23 05:36 UTC, merged

2021-07-23 05:39 UTC, alvarotorrestx commented
Definitely welcome and thank you for letting me contribute! I'll continue to follow to see if I'm able to continue helping! 😁